server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:com/project/mapper/*.xml
  type-aliases-package: com.project.pojo.entities
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

system:
  jwt:
    user-secret-key: user
    user-ttl: 7200000
    user-token-name: authentication
